apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-config
data:
  AWS_REGION: "us-east-1"
  BEDROCK_MODEL_ID: "anthropic.claude-3-haiku-20240307-v1:0"
---
apiVersion: v1
kind: Secret
metadata:
  name: llm-secrets
type: Opaque
data:
  POSTGRES_DB: bGxtX2FwcA==
  POSTGRES_USER: bGxtX3VzZXI=
  POSTGRES_PASSWORD: bGxtX3Bhc3N3b3Jk

